name: 'Stale Issue Report Generator'
description: 'Generates a gist report of open, stale issues that have not had a new comment posted within a specified daily threshold'
author: 'rob-derosa@github.com'
branding:
  icon: alert-triangle
  color: red
inputs:
  labels:
    required: true
    description: 'A comma delimited list of labels with amount of days (i.e. blocker=14,critical=30,important=60)'
  buffer:
    required: false
    description: 'The amount of days prior to the assigned label cutoff (i.e. a value of 3 would include blocker issues with no new comments within the last 11 days instead of 14)'
    default: '0'
  github-token:
    required: true
    description: 'A PAT that has the ability to read repos and post gists'
outputs:
  report-url:
      description: 'A url to the generated gist report'
runs:
  using: 'node12'
  main: 'dist/index.js'